name: Bump PCF Version

on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  #    - develop

jobs:
  bump-pcf:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Add pac to PATH
        shell: pwsh
        run: |
            echo "$env:USERPROFILE\.pac\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append


      - name: Bump version
        id: bump
        shell: bash
        run: |
          current="${{ vars.PCF_VERSION }}"
          echo "current version=$current"

          major=$(echo $current | cut -d. -f1)
          minor=$(echo $current | cut -d. -f2)
          build=$(echo $current | cut -d. -f3)
          new_build=$((build+1))
          new="$major.$minor.$new_build"
          echo "new=$new" >> $GITHUB_OUTPUT

      - name: Update ControlManifest.Input.xml
        run: |
          (Get-Content AssessmentPCFControl/AssessmentControl/ControlManifest.Input.xml) `
          -replace 'version="([0-9\.]+)"', 'version="${{ steps.bump.outputs.new }}"' `
          | Set-Content AssessmentPCFControl/AssessmentControl/ControlManifest.Input.xml

      - name: Update Solution.xml
        run: |
          (Get-Content src/Other/Solution.xml) `
          -replace '<Version>[0-9\.]+</Version>', "<Version>${{ steps.bump.outputs.new }}</Version>" `
          | Set-Content src/Other/Solution.xml

      - name: Build PCF
        shell: pwsh
        run: |
          cd AssessmentPCFControl
          npm install
          npm run build
          cd ..
          pac solution add-reference --path "AssessmentPCFControl"
          dotnet build AssessmentPCF.cdsproj /p:Configuration=Release

      - name: Commit + push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Bump PCF version to ${{ steps.bump.outputs.new }}"
          git push origin HEAD

      - name: Update GitHub Variable PCF_VERSION
        run: |
          curl -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/actions/variables/PCF_VERSION \
          -d "{\"value\":\"${{ steps.bump.outputs.new }}\"}"

      - name: Create Git Tag
        run: |
          git tag v${{ steps.bump.outputs.new }}
          git push origin v${{ steps.bump.outputs.new }}
